Fix compilation error for DMAv2 with kernel 6.1.94
Compilation error was seen with 6.1.94 on x86_64 target.

error: implicit declaration of function 'phys_to_page'; did you mean 'pmd_to_page'

'phys_to_page' was depricated function. Hence change it to use pfn_to_page(__phys_to_pfn(addr)).

Signed-off-by: Pavan Naregundi <pnaregundi@marvell.com>